http:
  routers:
    orders:
      entryPoints: [web]
      rule: (Host(`localhost`) || Host(`127.0.0.1`)) && (PathPrefix(`/orders`) || PathPrefix(`/demo`))
      service: order
    products:
      entryPoints: [web]
      rule: (Host(`localhost`) || Host(`127.0.0.1`)) && PathPrefix(`/products`)
      service: product
    inventory:
      entryPoints: [web]
      rule: (Host(`localhost`) || Host(`127.0.0.1`)) && (PathPrefix(`/inventory`) || PathPrefix(`/reservations`))
      service: inventory
    payments:
      entryPoints: [web]
      rule: (Host(`localhost`) || Host(`127.0.0.1`)) && PathPrefix(`/payments`)
      service: payment
    ui:
      entryPoints: [web]
      rule: (Host(`localhost`) || Host(`127.0.0.1`)) && PathPrefix(`/ui`)
      middlewares: [strip-ui]
      service: ui
  middlewares:
    strip-ui:
      stripPrefix:
        prefixes: [/ui]
  services:
    order:
      loadBalancer:
        servers: [{url: "http://order-service:8080"}]
    product:
      loadBalancer:
        servers: [{url: "http://product-service:8080"}]
    inventory:
      loadBalancer:
        servers: [{url: "http://inventory-service:8080"}]
    payment:
      loadBalancer:
        servers: [{url: "http://payment-service:8080"}]
    ui:
      loadBalancer:
        servers: [{url: "http://demo-ui:80"}]
