server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  resolver 127.0.0.11 valid=5s ipv6=off;
  location ~ ^/(demo|orders|products|inventory|reservations|payments)(/|$) {
    set $gateway http://traefik;
    proxy_set_header Host $http_host;
    proxy_read_timeout 20s;
    proxy_pass $gateway$request_uri;
  }
  location / { try_files $uri $uri/ /index.html; }
}
